services:
  graph_three:
    # cgroup_parent: /docker_executor
    # cpuset: "0,1"
    image: postgres:latest
    container_name: graph_three
    volumes:
      - graph_three:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8000:5432"


  graph_unified:
    # cgroup_parent: /docker_executor
    # cpuset: "0,1"
    image: postgres:latest
    container_name: graph_unified
    volumes:
      - graph_unified:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8001:5432"


  graph_jsonb:
    # cgroup_parent: /docker_executor
    # cpuset: "0,1"
    image: postgres:latest
    container_name: graph_jsonb
    volumes:
      - graph_jsonb:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8002:5432"


  graph_vertice:
    # cgroup_parent: /docker_executor
    # cpuset: "0,1,2,3,4,5"
    image: postgres:latest
    container_name: graph_vertice
    volumes:
      - graph_vertice:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8003:5432"


  graph_edge:
    # cgroup_parent: /docker_executor
    # cpuset: "0,1,2,3,4,5"
    image: postgres:latest
    container_name: graph_edge
    volumes:
      - graph_edge:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8004:5432"


  # test:
    # image: postgres:latest
    # container_name: test
    # environment:
    #   - POSTGRES_HOST_AUTH_METHOD=trust
    #   - POSTGRES_PASSWORD=postgres
    #   - PGDATA=/var/lib/postgresql/data/pgdata
    # ports:
    #   - "9000:5432"

networks:
  default:
    driver: bridge
    enable_ipv6: false

name: graph_pg_cluster

volumes:
  graph_three:
    name: graph_three
  graph_unified:
    name: graph_unified
  graph_jsonb:
    name: graph_jsonb
  graph_vertice:
    name: graph_vertice
  graph_edge:
    name: graph_edge
