services:
  graph_three:
    shm_size: '5gb'
    image: postgres:latest
    container_name: graph_three
    volumes:
      - graph_three:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8000:5432"

  graph_three_idx:
    shm_size: '5gb'
    image: postgres:latest
    container_name: graph_three_idx
    volumes:
      - graph_three_idx:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8005:5432"


  graph_unified:
    shm_size: '5gb'
    image: postgres:latest
    container_name: graph_unified
    volumes:
      - graph_unified:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8001:5432"


  graph_jsonb:
    shm_size: '5gb'
    image: postgres:latest
    container_name: graph_jsonb
    volumes:
      - graph_jsonb:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8002:5432"


  graph_vertice:
    shm_size: '5gb'
    image: postgres:latest
    container_name: graph_vertice
    volumes:
      - graph_vertice:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8003:5432"


  graph_edge:
    shm_size: '5gb'
    image: postgres:latest
    container_name: graph_edge
    volumes:
      - graph_edge:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8004:5432"

  neo4j_separated:
    image: neo4j
    container_name: neo4j_separated
    volumes:
      - neo4j_separated:/data
    environment:
      - NEO4J_AUTH=neo4j/password
      # - NEO4J_server_memory_heap_initial__size=11000m
      # - NEO4J_server_memory_heap_max__size=11000m
      # - NEO4J_server_memory_pagecache_size=1200m
      - NEO4J_server_memory_heap_initial__size=5000m
      - NEO4J_server_memory_heap_max__size=5000m
      - NEO4J_server_memory_pagecache_size=1200m
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_jvm_additional='-XX:+ExitOnOutOfMemoryError'
      - NEO4J_dbms_jvm_additional=-XX:NativeMemoryTracking=detail
    ports:
      - "3010:7687"
      - "3011:7474"

  neo4j_unified:
    image: neo4j
    container_name: neo4j_unified
    volumes:
      - neo4j_unified:/data
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_memory_heap_initial__size=11000m
      - NEO4J_server_memory_heap_max__size=11000m
      - NEO4J_server_memory_pagecache_size=1200m
      # - NEO4J_server_memory_heap_initial__size=5000m
      # - NEO4J_server_memory_heap_max__size=5000m
      # - NEO4J_server_memory_pagecache_size=1200m
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_jvm_additional='-XX:+ExitOnOutOfMemoryError'
      - NEO4J_dbms_jvm_additional=-XX:NativeMemoryTracking=detail
    ports:
      - "3020:7687"
      - "3021:7474"

  mongodb_unified:
    image: mongo
    container_name: mongodb_unified
    mem_limit: 9000m
    volumes:
      - mongodb_unified:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "4001:27017"

networks:
  default:
    driver: bridge
    enable_ipv6: false

name: graph_pg_cluster

volumes:
  graph_three:
    name: graph_three
  graph_three_idx:
    name: graph_three_idx
  graph_unified:
    name: graph_unified
  graph_jsonb:
    name: graph_jsonb
  graph_vertice:
    name: graph_vertice
  graph_edge:
    name: graph_edge
  neo4j_separated:
    name: neo4j_separated
  neo4j_unified:
    name: neo4j_unified
  # neo4j:
  #   name: neo4j
  mongodb_unified:
    name: mongodb_unified
