services:
  graph_three:
    shm_size: '5gb'
    image: postgres:latest
    container_name: graph_three
    volumes:
      - graph_three:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8000:5432"


  graph_unified:
    shm_size: '5gb'
    image: postgres:latest
    container_name: graph_unified
    volumes:
      - graph_unified:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8001:5432"


  graph_jsonb:
    shm_size: '5gb'
    image: postgres:latest
    container_name: graph_jsonb
    volumes:
      - graph_jsonb:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8002:5432"


  graph_vertice:
    shm_size: '5gb'
    image: postgres:latest
    container_name: graph_vertice
    volumes:
      - graph_vertice:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8003:5432"


  graph_edge:
    shm_size: '5gb'
    image: postgres:latest
    container_name: graph_edge
    volumes:
      - graph_edge:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8004:5432"

  neo4j_separated:
    image: neo4j
    container_name: neo4j_separated
    volumes:
      - neo4j_separated:/data
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "3011:7687"
      - "3010:7474"


  # test:
    # image: postgres:latest
    # container_name: test
    # environment:
    #   - POSTGRES_HOST_AUTH_METHOD=trust
    #   - POSTGRES_PASSWORD=postgres
    #   - PGDATA=/var/lib/postgresql/data/pgdata
    # ports:
    #   - "9000:5432"

networks:
  default:
    driver: bridge
    enable_ipv6: false

name: graph_pg_cluster

volumes:
  graph_three:
    name: graph_three
  graph_unified:
    name: graph_unified
  graph_jsonb:
    name: graph_jsonb
  graph_vertice:
    name: graph_vertice
  graph_edge:
    name: graph_edge
  neo4j_separated:
    name: neo4j_separated
